-- ORACLE_23AI.sql
-- Declaración de tablas y relaciones para Oracle 23ai basada en el modelo entidad-relación

CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR) NOT NULL,
    address VARCHAR2(200 CHAR),
    contact VARCHAR2(50 CHAR),
    username VARCHAR2(50 CHAR) UNIQUE NOT NULL,
    password VARCHAR2(100 CHAR) NOT NULL
);

COMMENT ON COLUMN customer.customer_id IS 'Identificador único del cliente';
COMMENT ON COLUMN customer.name IS 'Nombre completo del cliente';
COMMENT ON COLUMN customer.address IS 'Dirección del cliente';
COMMENT ON COLUMN customer.contact IS 'Información de contacto del cliente';
COMMENT ON COLUMN customer.username IS 'Nombre de usuario único';
COMMENT ON COLUMN customer.password IS 'Contraseña encriptada del usuario';

CREATE TABLE account (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    type VARCHAR2(30 CHAR) NOT NULL,
    balance NUMBER(15,2) DEFAULT 0,
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

COMMENT ON COLUMN account.account_id IS 'Identificador único de la cuenta';
COMMENT ON COLUMN account.customer_id IS 'Identificador del cliente propietario';
COMMENT ON COLUMN account.type IS 'Tipo de cuenta bancaria';
COMMENT ON COLUMN account.balance IS 'Saldo actual de la cuenta';

CREATE TABLE beneficiary (
    beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    account_number VARCHAR2(30 CHAR) NOT NULL,
    bank_details VARCHAR2(200 CHAR),
    CONSTRAINT fk_beneficiary_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

COMMENT ON COLUMN beneficiary.beneficiary_id IS 'Identificador único del beneficiario';
COMMENT ON COLUMN beneficiary.customer_id IS 'Identificador del cliente que registra al beneficiario';
COMMENT ON COLUMN beneficiary.name IS 'Nombre del beneficiario';
COMMENT ON COLUMN beneficiary.account_number IS 'Número de cuenta del beneficiario';
COMMENT ON COLUMN beneficiary.bank_details IS 'Detalles bancarios del beneficiario';

CREATE TABLE transaction (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    type VARCHAR2(20 CHAR) NOT NULL,
    amount NUMBER(15,2) NOT NULL CHECK (amount > 0),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account(account_id),
    CONSTRAINT chk_transaction_type CHECK (type IN ('deposit', 'withdrawal', 'transfer'))
);

COMMENT ON COLUMN transaction.transaction_id IS 'Identificador único de la transacción';
COMMENT ON COLUMN transaction.account_id IS 'Identificador de la cuenta asociada';
COMMENT ON COLUMN transaction.type IS 'Tipo de transacción';
COMMENT ON COLUMN transaction.amount IS 'Monto de la transacción';
COMMENT ON COLUMN transaction.timestamp IS 'Fecha y hora de la transacción';